run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Standard Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - revive        # General purpose linter
    - typecheck     # Type check

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Field alignment is a micro-optimization, prioritize readability

  staticcheck:
    checks: ["all"]

  revive:
    confidence: 0.8

issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
